services:
    postgres:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345
        POSTGRES_DB: bigdata_lab1
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
