DROP TABLE IF EXISTS f_sale;

DROP TABLE IF EXISTS d_customer;
DROP TABLE IF EXISTS d_seller;
DROP TABLE IF EXISTS d_product;
DROP TABLE IF EXISTS d_store;
DROP TABLE IF EXISTS d_supplier;
DROP TABLE IF EXISTS d_date;
