DROP TABLE IF EXISTS f_sale;

DROP TABLE IF EXISTS d_customer;
DROP TABLE IF EXISTS d_seller;
DROP TABLE IF EXISTS d_product;
DROP TABLE IF EXISTS d_store;
DROP TABLE IF EXISTS d_supplier;
DROP TABLE IF EXISTS d_date;

DROP TABLE IF EXISTS d_location;
DROP TABLE IF EXISTS d_pet;
DROP TABLE IF EXISTS d_product_category;
DROP TABLE IF EXISTS d_product_details;
DROP TABLE IF EXISTS d_product_rating;
DROP TABLE IF EXISTS d_product_dates;
